DROP SEQUENCE BOARDNOSEQ;
DROP SEQUENCE GROUPNOSEQ;
DROP TABLE ANSWERBOARD;

CREATE SEQUENCE BOARDNOSEQ;
CREATE SEQUENCE GROUPNOSEQ;

--글 번호, 그룹번호, 그룹순서, 제목텝, 삭제여부(N, Y)
--제목, 내용, 작성자, 작성일 

CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER NOT NULL,
	GROUPNO NUMBER NOT NULL,
	GROUPSEQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	DELFLAG VARCHAR2(2) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(500) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTANT BOARD_PK PRIMARY KEY(BOARDNO),
	CONSTANT DELFLAG_CHK CHECK(DELFLAG IN('Y', 'N'))
);
CREATE TABLE ANSWERBOARD(
   BOARDNO NUMBER NOT NULL,
   GROUPNO NUMBER NOT NULL,
   GROUPSEQ NUMBER NOT NULL,
   TITLETAB NUMBER NOT NULL,
   DELFLAG VARCHAR2(2) NOT NULL,
   TITLE VARCHAR2(1000) NOT NULL,
   CONTENT VARCHAR2(4000) NOT NULL,
   WRITER VARCHAR2(500) NOT NULL,
   REGDATE DATE NOT NULL,
   CONSTRAINT ANSWERBOARD_PK_BOARDNO PRIMARY KEY(BOARDNO),
   CONSTRAINT ANSWERBOARD_CHK_DELFLAG CHECK (DELFLAG IN ('Y','N'))
);