--DB에서 테이블을 만들고 값을 넣는다.

CREATE SEQUENCE NEXT;

CREATE TABLE BOARDTEST(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(20) NOT NULL,
	MYTITLE VARCHAR2(100) NOT NULL,
	MYCONTENT VARCHAR2(500) NOT NULL,
	MYDATE DATE NOT NULL
);

INSERT INTO BOARDTEST
VALUES(NEXT.NEXTVAL, '관리자','공지사항','없습니다.',SYSDATE);

SELECT * FROM BOARDTEST;