DROP TABLE MYMEMBER;

CREATE SEQUENCE MYNOSEQ;

--번호, ID, PW, 이름, 주소, 전화번호, 이메일, 가입여부(가입:Y, 탈퇴:N), 등급(ADMIN, USER, MANAGER)
CREATE TABLE MYMEMBER(
	MYNO NUMBER NOT NULL,			--PRIMARY KEY
	MYID VARCHAR2(500) NOT NULL,	--UNIQUE
	MYPW VARCHAR2(500) NOT NULL,	
	MYNAME VARCHAR2(500) NOT NULL,	
	MYADDR VARCHAR2(2000) NOT NULL,	
	MYPHONE VARCHAR2(20) NOT NULL,	--UNIQUE
	MYEMAIL VARCHAR2(100) NOT NULL,	--UNIQUE
	MYENABLED VARCHAR2(2) NOT NULL,	--CHECK(Y,N)
	MYROLE VARCHAR2(20) NOT NULL,
	CONSTRAINT PK01 PRIMARY KEY(MYNO),
	CONSTRAINT UN_ID UNIQUE(MYID),
	CONSTRAINT UN_PHONE UNIQUE(MYPHONE),
	CONSTRAINT UN_EMAIL UNIQUE(MYEMAIL),
	CONSTRAINT CHK01 CHECK(MYENABLED IN('Y', 'N'))
	);
	
	INSERT INTO MYMEMBER
	VALUES( MYNOSEQ.NEXTVAL, 'ID1', 'PW1', '관리자', '미국 워싱턴', '010-0000-0000', 'ABC@KH.COM', 'Y', 'ADMIN' );
	
	SELECT MYNO, MYID, MYPW, MYNAME, MYADDR, MYPHONE, MYEMAIL, MYENABLED, MYROLE FROM MYMEMBER ORDER BY MYNO DESC;