DROP SEQUENCE MYTESTSEQ;
DROP TABLE MYTEST;

CREATE SEQUENCE MYTESTSEQ;

CREATE TABLE MYTEST(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(500) NOT NULL,
	MYTITLE VARCHAR2(1000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL
);

INSERT INTO MYTEST
VALUES ( MYTESTSEQ.NEXTVAL, '김지후', '2번째연습', 'JSP', SYSDATE );

INSERT INTO MYTEST
VALUES ( MYTESTSEQ.NEXTVAL, '누구세요', '3번째연습', 'JSP', SYSDATE );

UPDATE MYTEST SET MYTITLE = '확인중', MYCONTENT = '테스트중입니다.' WHERE MYNO = 1;

SELECT * FROM MYTEST;