CREATE SEQUENCE NUMBERNEXT;
CREATE TABLE COMTEST(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(100) NOT NULL,
	MYTITLE VARCHAR2(200) NOT NULL,
	MYCONTENT VARCHAR2(400) NOT NULL,
	MYDATE DATE NOT NULL
);

INSERT INTO COMTEST
VALUES(NUMBERNEXT.NEXTVAL, '관리자', '내용은이겁니다.', '제목은 이겁니다.', SYSDATE);

SELECT * FROM COMTEST;